version: '3'

services:
  nginx:
    image: nginx:1.25.3-alpine3.18-slim
    container_name: nginx_con
    restart: always
    volumes:
      - ./ssl:/ssl
      - ./config/conf.d:/etc/nginx/conf.d
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/config.io:/etc/nginx/config.io
      - ./logs:/logs
    network_mode: 'host'
